apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: {{ .Release.Name }}-firefox-scaledobject
  namespace: selenium
  labels:
    deploymentName: {{ .Release.Name }}-node-firefox
spec:
  minReplicaCount: {{ .Values.minReplicaCount }}
  maxReplicaCount: {{ .Values.maxReplicaCount }}
  scaleTargetRef:
    name: {{ .Release.Name }}-node-firefox
    envSourceContainerName: selenium-node-firefox
  triggers:
    - type: "{{ .Values.triggers.type }}"
      metadata:
        url: '{{ .Values.triggers.metadata.url }}'  #this is selenium grid URL, external IP of Loadbalancer
        browserName: '{{ .Values.triggers.metadata.browserName2 }}'