apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-node-firefox
  namespace: selenium
  labels:
    app: {{ .Release.Name }}-node-firefox
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-node-firefox
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-node-firefox
    spec:
      terminationGracePeriodSeconds: 3600
      volumes:
      - name: dshm
        emptyDir:
          medium: Memory
      containers:
      - name: selenium-node-firefox
        image: selenium/node-firefox:4.16
        ports:
          - containerPort: 5555
        volumeMounts:
          - mountPath: /dev/shm
            name: dshm
        env:
          - name: SE_EVENT_BUS_HOST
            value: {{ .Release.Name }}-hub-svc
          - name: SE_EVENT_BUS_SUBSCRIBE_PORT
            value: "4443"
          - name: SE_EVENT_BUS_PUBLISH_PORT
            value: "4442"
        resources:
          limits:
            memory: "1000Mi"
            cpu: ".5"
        lifecycle:
          preStop:
            exec:
              command: ["/bin/sh", "-c", "curl --request POST 'localhost:5555/se/grid/node/drain' --header 'X-REGISTRATION-SECRET;'; tail --pid=$(pgrep -f '[n]ode --bind-host false --config /opt/selenium/config.toml') -f /dev/null; sleep 30s"]