apiVersion: apps/v1
kind: Deployment
metadata:
  name:  {{ .Release.Name }}-hub
  namespace: selenium
  labels:
    app:  {{ .Release.Name }}-hub
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}-hub
  replicas: 1
  template:
    metadata:
      labels:
        app:  {{ .Release.Name }}-hub
    spec:
      containers:
      - name:  {{ .Release.Name }}-hub
        image:  "{{ .Values.image.repositoryhub }}:{{ .Values.image.taghub }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        resources:
          requests:
            cpu: {{ .Values.resources.requests.cpu }}
            memory: {{ .Values.resources.requests.memory }}
          limits:
            cpu: {{ .Values.resources.limits.cpu }}
            memory: {{ .Values.resources.limits.memory }}
        livenessProbe:
          httpGet:
            path: {{ .Values.livenessProbe.httpGet.path }}
            port: {{ .Values.livenessProbe.httpGet.port }}
          initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
          timeoutSeconds: {{ .Values.livenessProbe.timeoutSeconds }}
        readinessProbe:
          httpGet:
            path: {{ .Values.readinessProbe.httpGet.path }}
            port: {{ .Values.readinessProbe.httpGet.port }}
          initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
          timeoutSeconds: {{ .Values.readinessProbe.timeoutSeconds }}
        ports:
        - containerPort: {{ .Values.ports.port1 }}
        - containerPort: {{ .Values.ports.port2 }}
        - containerPort: {{ .Values.ports.port3 }}
      restartPolicy: Always