apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/name: keda-system-auth-delegator
    app.kubernetes.io/part-of: keda-operator
    app.kubernetes.io/version: {{ .Values.version }}
  name: keda-system-auth-delegator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
subjects:
- kind: ServiceAccount
  name: keda-operator
  namespace: keda