# Default values for keda.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
version: 2.8.0
image:
  keda:
    name: ghcr.io/kedacore/keda
    imageVersion: 2.8.0
  kedaMetrics:
    name: ghcr.io/kedacore/keda-metrics-apiserver
    imageVersion: 2.8.0