apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
spec:
  selector:
    matchLabels:
      app: auth-service
  replicas: 1
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
        - name: auth-service
          image: localhost:5000/dethrone-auth:latest
          ports:
            - containerPort: 3000
          env:
            - name: PORT
              value: "3000"
            - name: HOST
              value: "0.0.0.0"
            - name: DB_CONNECTION_URL
              value: "mongodb://mongodb/auth"
            - name: SROUNDS
              value: "10"
            - name: JWT_SECRET_KEY
              value: "okxUuOsWwtZaBf7ZCdojxC79OfddgXEMwDUSWgVNuNi2OsdpRSxZOxymS04hsKVG"