apiVersion: v1
kind: Service
metadata:
  name: web-central-service
spec:
  selector:
    app: web-central
  ports:
    - protocol: TCP
      port: 3004
      targetPort: 3004
  type: LoadBalancer