apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-mongodb
spec:
  selector:
    app: {{ .Release.Name }}-mongodb
  ports:
    - protocol: TCP
      port: {{ .Values.service.mango.ports.port }}
      targetPort: {{ .Values.service.mango.ports.targetport }}